### ISSUE TITLE
Relationship to different "Wild.ID" project 

### ISSUE THREAD

**Issue by jvolker** [ConservationInternational/Wild.ID#8]
Hi, 

I'm just trying to understand how this project works and what it's capable of. I've noticed there is another project on the internet called the same "Wild.ID". They seem to have the same name but looks like the authors are not the same. Also, the features and purpose seem to be different.

What's the relationship between this project and https://www.wildid.app/?

Thanks.

**Comment by eric-fegraus** [comment]
No relationship between the two projects.
