### ISSUE TITLE
Version numbers out of sync

### ISSUE THREAD

**Issue by jvolker** [ConservationInternational/Wild.ID#9]
I just recognised the version numbers of this project seem to be out of sync. Just wanted to let you know. https://github.com/ConservationInternational/Wild.ID/releases/tag/0.9.32 actually shows up as 1.0.2 after opening it.

![image](https://user-images.githubusercontent.com/546852/125654551-eda66899-3e3d-4527-b865-ed056d4e496a.png)

Also, here only 1.0.1 is available, not 1.0.2: http://35.188.216.67:8080/Wild.ID/download.jsp

**Comment by eric-fegraus** [comment]
Hi,
Thanks for the feedback. We will get this lined up. Development on this project is closed and will deprecated in the next year or so. All new development has transitioned to wildlifeinsights.org. In addition to the cloud based application a companion client (desktop/laptop) will be available in late 2021 and early 2022.
